api_version = "2025-01"
uid = "d71b01d3-dccb-3d16-1c2a-cc7818e5e0932046a4f7"
type = "theme"

[settings]
name = "LockerDrop Theme Blocks"

[[metafields]]
namespace = "lockerdrop"
key = "locker_eligible"
